### ISSUE TITLE
Latest Release

### ISSUE THREAD

**Issue by andrewwljackson** [wwww-wwww/phxsocket#1]
Hi there, 

This repo looks awesome. Pip installing phxsocket seems to install an earlier version of your code. Could you release the latest version? I'm excited to try and use it!

Thanks so much

**Comment by wwww-wwww** [comment]
Latest release should be on PyPI now. Let me know if you have any issues.

**Comment by andrewwljackson** [comment]
There is an issue with the naming/import of the Message.py file. I forked and renamed it just to start using it, but maybe rename the Message.py file to message.py for the imports in the client directory
